// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.JWTDecoder
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("header")]
        public Header Header { get; set; }

        [JsonProperty("payload")]
        public Payload Payload { get; set; }

        [JsonProperty("signature")]
        public string Signature { get; set; }

        [JsonProperty("isExpired")]
        public bool IsExpired { get; set; }

        [JsonProperty("expiresAt")]
        public object ExpiresAt { get; set; }

        [JsonProperty("warning")]
        public string Warning { get; set; }
    }

    public partial class Header
    {
        [JsonProperty("alg")]
        public string Alg { get; set; }

        [JsonProperty("typ")]
        public string Typ { get; set; }
    }

    public partial class Payload
    {
        [JsonProperty("sub")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Sub { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("iat")]
        public long Iat { get; set; }
    }
}
